package controller;

import models.PersonSocial;

public enum MainActivity {
	ACCEPT_PERSONS, LEAVE_THE_SOCIAL_NETWORK, MUTUAL_FRIENDS, ADD_FRIEND, DELETE_FRIEND, SHOW_PERSONS, ADD_FRIEND_FINALLY, DELETE_FRIEND_FINALLY, DELETE_PERSON,
	 LEAVE_NETWORK_FINALLY, LEAVE_NETWORK

}
